version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - housewars-sqlite3:/var/www/housewars/db
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: "CollegiateHouseWars.settings.test"
    command: python manage.py test
volumes:
  housewars-sqlite3:
