version: '3.8'

name: 'collegiate-housewars'
services:
  app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - housewars
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: "CollegiateHouseWars.settings.dev"
    depends_on:
      - mysqldb
  mysqldb:
    restart: unless-stopped
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - housewars-mysql:/var/lib/mysql
    networks:
      - housewars
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: prod
volumes:
  housewars-mysql:
networks:
  housewars: {}
