name: Test build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup Chrome
        uses: nanasess/setup-chromedriver@v1.0.8
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Test build
        run: python manage.py test
